WebClient/Models/ViewModels.cs
using Model;
using System;

namespace WebClient.Models
{
    public class WellsViewModel
    {
        public ResponceAndDataList<WellDto> WellsResponce { get; set; }
        public Guid DepositId { get; set; }
        public string DepositName { get; set; }
    }

    public class ExtractionsViewModel
    {
        public ResponceAndDataList<ExtractionDto> ExtractionResponce { get; set; }
        public Guid WellId { get; set; }
        public string WellNumber { get; set; }
        public string DateFrom { get; set; }
        public string DateTo { get; set; }
    }
}

WebClient/Controllers/DataController.cs
using Model;
using System;
using System.Web.Mvc;
using WebClient.DataService;
using WebClient.Models;

namespace WebClient.Controllers
{
    public class DataController : Controller
    {
        public ActionResult Deposits()
        {
            DataServiceClient client = new DataServiceClient();
            var model = client.ReadDeposits();
            client.Close();

            return View(model);
        }

        public ActionResult Wells(Guid depositId, string depositName)
        {
            DataServiceClient client = new DataServiceClient();
            var wellsResponce = client.ReadWells(depositId);
            client.Close();

            var model = new WellsViewModel
            {
                DepositId = depositId,
                DepositName = depositName,
                WellsResponce = wellsResponce
            };

            return View(model);
        }

        public ActionResult Extractions(Guid wellId, string wellNumber, string dateFrom, string dateTo)
        {
            DateTime _dateFrom;
            DateTime _dateTo;

            DateTime.TryParse(dateFrom, out _dateFrom);
            DateTime.TryParse(dateTo, out _dateTo);

            DataServiceClient client = new DataServiceClient();
            var extractionsResponce = client.ReadExtractions(wellId, _dateFrom.ToString(StringHelper.dateFormat), _dateTo.ToString(StringHelper.dateFormat));
            client.Close();

            var model = new ExtractionsViewModel
            {
                WellId = wellId,
                WellNumber = wellNumber,
                DateFrom = _dateFrom.ToString("dd/MM/yyyy"),
                DateTo = _dateTo.ToString("dd/MM/yyyy"),
                ExtractionResponce = extractionsResponce
            };

            return View(model);
        }
    }
}

WebClient/Views/Data/Deposits.cshtml
@using Model
@model ResponceAndDataList<DepositDto>
@{
    ViewBag.Title = "Месторождения";
}

<h3>Список месторождений</h3>

@if (Model.Responce.Succeded)
{
    if (Model.Data.Any())
    {
        var number = 1;
        <div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Название</th>
                        <th scope="col" class="col-md-3">Скважины месторождения</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var deposit in Model.Data)
                    {
                        <tr id="@deposit.ID">
                            <td>@number</td>
                            <td>@deposit.Name</td>
                            <td class="centered">
                                <a href="@Url.Action("Wells","Data", new { depositId = deposit.ID, depositName = deposit.Name })"><i class="glyphicon glyphicon-circle-arrow-right"></i></a>
                            </td>
                        </tr>
                        number++;
                    }
                </tbody>
            </table>
        </div>

        <br />
    }
    else
    {
        <div style="margin: 10px">
            <span>Месторождения не найдены</span>
        </div>
    }
}
else
{
    <span>При обработке запроса произошла ошибка.</span>
    <span>@Model.Responce.ErrorMessage</span>
}

WebClient/Views/Data/Extractions.cshtml
@using WebClient.Models
@model ExtractionsViewModel
@{
    ViewBag.Title = "Добычи";
}

<h3>Добычи скважины "@Model.WellNumber" c @Model.DateFrom по @Model.DateTo</h3>

@if (Model.ExtractionResponce.Responce.Succeded)
{
    if (Model.ExtractionResponce.Data.Any())
    {
        var number = 1;
        <div>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col" class="col-md-3">Дата</th>
                        <th scope="col" class="col-md-3">Значение</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var extraction in Model.ExtractionResponce.Data)
                    {
                        <tr id="@extraction.ID">
                            <td>@number</td>
                            <td>@extraction.Date.ToString("dd.MM.yyyy")</td>
                            <td>@extraction.Value</td>
                        </tr>
                        number++;
                    }
                </tbody>
            </table>
        </div>

        <br />
    }
    else
    {
        <div style="margin: 10px">
            <span>Добычи не найдены</span>
        </div>
    }
}
else
{
    <span>При обработке запроса произошла ошибка.</span>
    <span>@Model.ExtractionResponce.Responce.ErrorMessage</span>
}

<button class="btn btn-outline-primary" onclick="ToDeposits()">К месторождениям</button>

<script>
    function ToDeposits() {
        window.location.href = "@Url.Action("Deposits", "Data")";
    }
</script>

WebClient/Views/Data/Wells.cshtml
@using WebClient.Models
@model WellsViewModel
@{
    ViewBag.Title = "Скважины";
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/css/bootstrap-datetimepicker.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.37/js/bootstrap-datetimepicker.min.js"></script>

<h3>Скважины месторождения "@Model.DepositName"</h3>

@if (Model.WellsResponce.Responce.Succeded)
{
    if (Model.WellsResponce.Data.Any())
    {
        var number = 1;
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Номер</th>
                    <th scope="col" class="col-md-3">Добычи</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var well in Model.WellsResponce.Data)
                {
                    <tr id="@well.ID">
                        <td>@number</td>
                        <td>@well.Number</td>

                        <td class="centered">
                            @Html.Raw("<a><i class=\"glyphicon glyphicon-circle-arrow-right\" onclick=\"selectWell('" + well.ID + "', '" + well.Number + "')\"></i></a>")
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div style="margin: 10px">
            <span>Скважины не найдены</span>
        </div>
    }
}
else
{
    <span>При обработке запроса произошла ошибка.</span>
    <span>@Model.WellsResponce.Responce.ErrorMessage</span>
}

<button class="btn btn-outline-primary" onclick="ToDeposits()">К месторождениям</button>

<div class="modal fade" id="date-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="exampleModalLabel">Выберите временной диапазон для фильрации добыч</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="date-picker-container">
                        <span>От:</span>
                        <input type='text'
                               class="form-control"
                               data-date-end-date="0"
                               id='datetimepicker1'
                               data-clear-btn="true"
                               autocomplete="off" />
                    </div>
                </div>
                <div class="row">
                    <div class="date-picker-container">
                        <span>До:</span>
                        <input type='text'
                               class="form-control"
                               data-date-end-date="0"
                               id='datetimepicker2'
                               data-clear-btn="true"
                               autocomplete="off" />
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Назад</button>
                <button type="button" class="btn btn-primary" onclick="submit()">К Добычам</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    let selectedWellId = undefined;
    let selectedWellNumber = undefined;


    $('#datetimepicker1').datetimepicker({
        format: 'DD/MM/YYYY',
        date: new Date(2019, 8, 1), // Сентябрь - в js первый месяц нулевой. Это бред. Года и дни с 1
        useCurrent: false
    });

    $('#datetimepicker2').datetimepicker({
        date: new Date(),
        format: 'DD/MM/YYYY',
    });

    $("#datetimepicker1").on("dp.change", function (e) {
        $('#datetimepicker2').data("DateTimePicker").minDate(e.date);
    });

    $("#datetimepicker2").on("dp.change", function (e) {
        $('#datetimepicker1').data("DateTimePicker").maxDate(e.date);
    });

    function selectWell(id, number) {
        selectedWellId = id;
        selectedWellNumber = number;
        $('#date-modal').modal('show');
    }

    function submit() {
        let dateForm = $('#datetimepicker1').val();
        let dateTo = $('#datetimepicker2').val();
        if (selectedWellId !== undefined) {
            window.location.href = `Extractions?wellId=${selectedWellId}&wellNumber=${selectedWellNumber}&dateFrom=${dateForm}&dateTo=${dateTo}`;
        }
    }

     function ToDeposits() {
        window.location.href = "@Url.Action("Deposits", "Data")";
    }
</script>

<style>
    .date-picker-container {
        padding: 15px;
    }

    .modal-header {
        padding: 10px;
        text-align: center;
        font-weight: bold;
    }
</style>

WebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "Deposits", "Data")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Системная интеграция ЛБ2</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>